# Generated by Django 5.2.1 on 2025-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agent_photos/'),
        ),
    ]
