# Generated by Django 5.2.1 on 2025-07-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ব্যয়ের ধরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ব্যয়ের নাম')),
                ('date', models.DateField(verbose_name='তারিখ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='টাকার পরিমাণ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sample.expensecategory', verbose_name='ব্যয় ক্যাটেগরি')),
            ],
        ),
    ]
