# Generated by Django 5.2.1 on 2025-07-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_expense_amount_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='ex_name',
        ),
    ]
