# Generated by Django 5.2.1 on 2025-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_rename_name_expense_ex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Expense Type'),
        ),
    ]
