# Generated by Django 5.2.1 on 2025-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_clientservices_created_by_delete_clientservicesusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
