# Generated by Django 5.2.1 on 2025-06-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0006_passportinfo'),
        ('services', '0005_serviceapplication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='passport_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_wizard.passportinfo'),
        ),
    ]
