# Generated by Django 5.2.1 on 2025-06-23 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serviceapplication_passport_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed discount amount on service price', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='discount_used',
            field=models.BooleanField(default=True, help_text='Indicates if discount has been used'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='payment_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_message', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Status Change', 'Status Change')], max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceapplication')),
            ],
        ),
    ]
