# Generated by Django 5.2.1 on 2025-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceapplication_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='action_taken',
            field=models.CharField(choices=[('none', 'None'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment'), ('payment_due_date', 'Payment Due Date'), ('status_change', 'Status Change')], default='none', help_text='Indicates the type of action taken for the service application', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='The date by which the full payment should be made', null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='action_taken',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment'), ('Status Change', 'Status Change')], max_length=255),
        ),
    ]
