# Generated by Django 5.2.1 on 2025-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceapplication_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservices',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='action_taken',
            field=models.CharField(choices=[('Partial Payment', 'Partial Payment'), ('Full Payment', 'Full Payment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='remaining_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='action_taken',
            field=models.CharField(choices=[('none', 'None'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment')], default='none', help_text='Indicates the type of action taken for the service application', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='discount',
            field=models.IntegerField(default=0, help_text='Fixed discount amount on service price'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='discount_used',
            field=models.BooleanField(default=False, help_text='Indicates if discount has been used'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
