# Generated by Django 5.2.1 on 2025-06-25 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_paymentlog_user_clientpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceapplication'),
        ),
    ]
