# Generated by Django 5.2.1 on 2025-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_clientpayment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpayment',
            name='admin_message',
            field=models.TextField(blank=True, null=True, verbose_name='অ্যাডমিন বার্তা'),
        ),
        migrations.AddField(
            model_name='clientpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'পেন্ডিং'), ('approved', 'অনুমোদিত'), ('rejected', 'বাতিল')], default='pending', max_length=20, null=True),
        ),
    ]
