# Generated by Django 5.2.1 on 2025-06-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_clientpayment_admin_message_clientpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment')], default='none', help_text='Indicates the type of action taken for the service application', max_length=20, null=True),
        ),
    ]
