# Generated by Django 5.2.1 on 2025-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_serviceapplication_action_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceapplication',
            name='action_taken',
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='amount_paid',
            field=models.IntegerField(default=0, verbose_name='পেমেন্ট পরিমাণ'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='আবেদনের তারিখ'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='discount',
            field=models.IntegerField(default=0, help_text='Fixed discount amount on service price', verbose_name='ডিসকাউন্ট'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='discount_used',
            field=models.BooleanField(default=False, help_text='Indicates if discount has been used', verbose_name='ডিসকাউন্ট ব্যবহৃত'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='বার্তা'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='The date by which the full payment should be made', null=True, verbose_name='পেমেন্ট Due তারিখ'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='payment_message',
            field=models.TextField(blank=True, null=True, verbose_name='পেমেন্ট বার্তা'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'আবেদন করা হয়েছে'), ('approved', 'অনুমোদিত'), ('rejected', 'বাতিল'), ('payment_pending', 'পেমেন্ট পেন্ডিং'), ('partial_payment', 'আংশিক পেমেন্ট'), ('full_payment', 'পূর্ণ পেমেন্ট'), ('ready', 'প্রস্তুত')], default='applied', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ'),
        ),
    ]
