# Generated by Django 5.2.1 on 2025-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_serviceapplication_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('applied', 'আবেদন করা হয়েছে'), ('payment_pending', 'পেমেন্ট পেন্ডিং রয়েছে'), ('full_payment', 'পেমেন্ট পরিষদ হয়েছে'), ('processing_job_permit', 'জব কন্টাক্ট/ওয়ার্ক পারমিট কাজটি প্রক্রিয়াধীন'), ('job_permit_received', 'জব কন্টাক্ট/ওয়ার্ক পারমিট রিসিভ করা হয়েছে'), ('visa_processing_third_country', 'তৃতীয় দেশের ভিসা আবেদন প্রক্রিয়াধীন'), ('embassy_approval_pending', 'এম্বাসি অ্যাপ্রুভ প্রক্রিয়াধীন'), ('visa_application_submitted', 'ভিসা অ্যাপ্লিকেশন জমা দেওয়া হয়েছে'), ('visa_decision', 'ভিসা এপ্রুভ / রিজেক্ট'), ('flight_date_confirmed', 'ফ্লাইট বুকিং ডেট সম্পন্ন')], default='applied', max_length=50, null=True, verbose_name='স্ট্যাটাস'),
        ),
    ]
