# Generated by Django 5.2.1 on 2025-06-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_serviceapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payment_services', to='services.serviceapplication'),
        ),
    ]
