# Generated by Django 5.2.1 on 2025-06-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_alter_clientpayment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='notice_message')),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/files/', verbose_name='notice_file')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/images/', verbose_name='notice_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='notice_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='notice_updated_date')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='services.clientservices', verbose_name='notice_service')),
            ],
        ),
    ]
