# Generated by Django 5.2.1 on 2025-06-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_notice_status_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('payment_pending', 'পেমেন্ট যাচাই চলমান'), ('partial_payment', 'আংশিক পেমেন্ট সম্পন্ন'), ('full_payment', 'পেমেন্ট পরিশোধ হয়েছে'), ('rejected', 'পেমেন্ট বাতিল হয়েছে')], default='applied', max_length=50, null=True, verbose_name='স্ট্যাটাস'),
        ),
        migrations.CreateModel(
            name='ServiceApplicationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'আবেদন করা হয়েছে'), ('payment_pending', 'পেমেন্ট পেন্ডিং রয়েছে'), ('full_payment', 'পেমেন্ট পরিষদ হয়েছে'), ('processing_job_permit', 'জব কন্টাক্ট/ওয়ার্ক পারমিট কাজটি প্রক্রিয়াধীন'), ('job_permit_received', 'জব কন্টাক্ট/ওয়ার্ক পারমিট রিসিভ করা হয়েছে'), ('visa_processing_third_country', 'তৃতীয় দেশের ভিসা আবেদন প্রক্রিয়াধীন'), ('embassy_approval_pending', 'এম্বাসি অ্যাপ্রুভ প্রক্রিয়াধীন'), ('visa_application_submitted', 'ভিসা অ্যাপ্লিকেশন জমা দেওয়া হয়েছে'), ('visa_decision', 'ভিসা এপ্রুভ / রিজেক্ট'), ('flight_date_confirmed', 'ফ্লাইট বুকিং ডেট সম্পন্ন')], default='applied', max_length=50, verbose_name='অবস্থা')),
                ('message', models.TextField(blank=True, null=True, verbose_name='মেসেজ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='services.serviceapplication', verbose_name='Service Application')),
            ],
        ),
    ]
