# Generated by Django 5.2.1 on 2025-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_serviceapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='action_taken',
            field=models.CharField(choices=[('payment_pending', 'পেমেন্ট যাচাই চলমান'), ('partial_payment', 'আংশিক পেমেন্ট সম্পন্ন'), ('full_payment', 'পেমেন্ট পরিশোধ হয়েছে'), ('rejected', 'পেমেন্ট বাতিল হয়েছে')], max_length=255),
        ),
    ]
