# Generated by Django 5.2.1 on 2025-06-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_paymentlog_action_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceapplicationprogress',
            unique_together={('application', 'status')},
        ),
    ]
