# Generated by Django 5.2.1 on 2025-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_serviceapplicationprogress_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='notice_title')),
                ('message', models.TextField(blank=True, null=True, verbose_name='notice_message')),
                ('file', models.FileField(blank=True, null=True, upload_to='notices_public/files/', verbose_name='public_notice_file')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices_public/images/', verbose_name='public_notice_image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='notice_status_public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='public_notice_date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='public_notice_updated_date')),
            ],
        ),
    ]
