# Generated by Django 5.2.1 on 2025-06-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagencycv',
            name='languages',
        ),
        migrations.RenameField(
            model_name='travelagencycv',
            old_name='language_other',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='travelagencycv',
            old_name='is_permanent_same_as_current',
            new_name='permanent_address_same',
        ),
        migrations.RemoveField(
            model_name='travelagencycv',
            name='blood_group_other',
        ),
        migrations.RemoveField(
            model_name='travelagencycv',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='travelagencycv',
            name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='travelagencycv',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='permanent_policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='permanent_postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='permanent_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='permanent_wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='policeStation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='postOffice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='postal_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelagencycv',
            name='wardNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelagencycv',
            name='current_job_status',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
