# Generated by Django 5.2.1 on 2025-06-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0002_remove_travelagencycv_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagencycv',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
