# Generated by Django 5.2.1 on 2025-06-16 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0003_alter_travelagencycv_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='travelagencycv',
            name='current_job_status',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='GuestCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name (English)')),
                ('full_name_bn', models.CharField(blank=True, max_length=200, verbose_name='Full Name (Bangla)')),
                ('skills', models.CharField(blank=True, help_text='Your main skill or expertise', max_length=200, null=True)),
                ('special_skills', models.CharField(blank=True, help_text='Any special skills you have', max_length=200, null=True)),
                ('bio', models.TextField(blank=True, help_text='A brief introduction about yourself')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('Other', 'Other')], default='Other', max_length=10)),
                ('blood_group_other', models.CharField(blank=True, help_text='If Other, specify here', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cv_pictures/')),
                ('language_other', models.CharField(blank=True, help_text='If Other, specify additional languages here', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.IntegerField(blank=True, help_text='National ID', null=True, unique=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('is_permanent_same_as_current', models.BooleanField(default=False)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fathers_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('fathers_nid', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mothers_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_nid', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, null=True)),
                ('married', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5, null=True)),
                ('last_education', models.CharField(blank=True, choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('HONOURS', 'Honours'), ('Others', 'Others')], default='SSC', max_length=20, null=True)),
                ('last_education_other', models.CharField(blank=True, help_text='If Others, specify here', max_length=100, null=True)),
                ('last_education_result', models.CharField(blank=True, max_length=100, null=True)),
                ('last_education_passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('current_job_status', models.CharField(blank=True, choices=[('Unemployed', 'Unemployed'), ('Employed', 'Employed'), ('Student', 'Student'), ('Others', 'Others')], default='Unemployed', max_length=20, null=True)),
                ('current_job_status_other', models.CharField(blank=True, help_text='If Others, specify here', max_length=100, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gust_cv', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='cvs', to='form_wizard.language')),
            ],
        ),
    ]
