# Generated by Django 5.2.1 on 2025-06-16 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0004_language_alter_travelagencycv_current_job_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_cv', to=settings.AUTH_USER_MODEL),
        ),
    ]
