# Generated by Django 5.2.1 on 2025-06-25 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0006_passportinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcv',
            name='current_job_status_other',
        ),
        migrations.RemoveField(
            model_name='guestcv',
            name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='guestcv',
            name='language_other',
        ),
        migrations.RemoveField(
            model_name='guestcv',
            name='languages',
        ),
        migrations.AddField(
            model_name='guestcv',
            name='language',
            field=models.CharField(blank=True, max_length=255, verbose_name='ভাষা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='bio',
            field=models.TextField(blank=True, help_text='সংক্ষিপ্ত নিজের পরিচয়', verbose_name='জীবনবৃত্তান্ত'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='Other', max_length=10, verbose_name='রক্তের গ্রুপ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='blood_group_other',
            field=models.CharField(blank=True, help_text='অন্যান্য হলে এখানে লিখুন', max_length=20, verbose_name='অন্যান্য রক্তের গ্রুপ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='current_address',
            field=models.TextField(blank=True, null=True, verbose_name='বর্তমান ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='current_job_status',
            field=models.CharField(blank=True, choices=[('Unemployed', 'বেকার'), ('Employed', 'চাকরিজীবী'), ('Student', 'ছাত্র/ছাত্রী'), ('Business', 'ব্যবসা'), ('Others', 'অন্যান্য')], default='Unemployed', max_length=20, null=True, verbose_name='বর্তমান পেশার অবস্থা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='জন্মতারিখ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='fathers_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='পিতার মোবাইল'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='পিতার নাম'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='fathers_nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='পিতার এনআইডি'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='পূর্ণ নাম (ইংরেজি)'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='full_name_bn',
            field=models.CharField(blank=True, max_length=100, verbose_name='পূর্ণ নাম (বাংলা)'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'পুরুষ'), ('Female', 'নারী'), ('Other', 'অন্যান্য')], default='Male', max_length=10, null=True, verbose_name='লিঙ্গ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='is_permanent_same_as_current',
            field=models.BooleanField(default=False, verbose_name='স্থায়ী ঠিকানা একই?'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='last_education',
            field=models.CharField(blank=True, choices=[('SSC', 'এসএসসি'), ('HSC', 'এইচএসসি'), ('HONOURS', 'স্নাতক'), ('Others', 'অন্যান্য')], default='SSC', max_length=20, null=True, verbose_name='সর্বশেষ শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='last_education_other',
            field=models.CharField(blank=True, help_text='অন্যান্য হলে লিখুন', max_length=100, null=True, verbose_name='অন্যান্য শিক্ষাগত যোগ্যতা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='last_education_passing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='পাসের বছর'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='last_education_result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ফলাফল'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='married',
            field=models.CharField(blank=True, choices=[('Yes', 'হ্যাঁ'), ('No', 'না')], default='No', max_length=5, null=True, verbose_name='বৈবাহিক অবস্থা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='mothers_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='মাতার মোবাইল'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='মাতার নাম'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='mothers_nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='মাতার এনআইডি'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='national_id',
            field=models.IntegerField(blank=True, help_text='জাতীয় পরিচয়পত্র নম্বর', null=True, unique=True, verbose_name='জাতীয় পরিচয়পত্র নম্বর'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='জাতীয়তা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='স্থায়ী ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='agent/client/cv_pictures/', verbose_name='প্রোফাইল ছবি'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='skills',
            field=models.CharField(blank=True, help_text='মূল দক্ষতা', max_length=200, null=True, verbose_name='দক্ষতা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='special_skills',
            field=models.CharField(blank=True, help_text='বিশেষ কোনো দক্ষতা থাকলে', max_length=200, null=True, verbose_name='বিশেষ দক্ষতা'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ'),
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_cv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'পুরুষ'), ('Female', 'মহিলা'), ('Other', 'অন্যান্য')], max_length=10, null=True),
        ),
    ]
