# Generated by Django 5.2.1 on 2025-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0007_remove_guestcv_current_job_status_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcv',
            name='blood_group_other',
        ),
        migrations.RemoveField(
            model_name='guestcv',
            name='last_education_other',
        ),
        migrations.AlterField(
            model_name='guestcv',
            name='married',
            field=models.CharField(blank=True, choices=[('Married', 'বিবাহিত'), ('Unmarried', 'অবিবাহিত')], default='Unmarried', max_length=10, null=True, verbose_name='বৈবাহিক অবস্থা'),
        ),
    ]
