# Generated by Django 5.2.1 on 2025-07-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0008_remove_guestcv_blood_group_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportinfo',
            name='agent',
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_1',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_2',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_3',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_4',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_5',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
        migrations.AddField(
            model_name='passportinfo',
            name='additional_file_6',
            field=models.FileField(blank=True, null=True, upload_to='passport/passport_additional_files/'),
        ),
    ]
