# Generated by Django 5.2.1 on 2025-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCvAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='পূর্ণ নাম (ইংরেজি)')),
                ('full_name_bn', models.CharField(blank=True, max_length=100, verbose_name='পূর্ণ নাম (বাংলা)')),
                ('phone', models.CharField(help_text='ফোন নম্বর (যেমনঃ 01XXXXXXXXX)', max_length=13, unique=True, verbose_name='ফোন নম্বর')),
                ('skills', models.CharField(blank=True, help_text='মূল দক্ষতা', max_length=200, null=True, verbose_name='দক্ষতা')),
                ('special_skills', models.CharField(blank=True, help_text='বিশেষ কোনো দক্ষতা থাকলে', max_length=200, null=True, verbose_name='বিশেষ দক্ষতা')),
                ('bio', models.TextField(blank=True, help_text='সংক্ষিপ্ত নিজের পরিচয়', verbose_name='জীবনবৃত্তান্ত')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='Other', max_length=10, verbose_name='রক্তের গ্রুপ')),
                ('blood_group_other', models.CharField(blank=True, help_text='অন্যান্য হলে এখানে লিখুন', max_length=20, verbose_name='অন্যান্য রক্তের গ্রুপ')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='agent/client/cv_pictures/', verbose_name='প্রোফাইল ছবি')),
                ('language', models.CharField(blank=True, max_length=255, verbose_name='ভাষা')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ইমেইল')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='জন্মতারিখ')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='জাতীয়তা')),
                ('national_id', models.IntegerField(blank=True, help_text='জাতীয় পরিচয়পত্র নম্বর', null=True, unique=True, verbose_name='জাতীয় পরিচয়পত্র নম্বর')),
                ('current_address', models.TextField(blank=True, null=True, verbose_name='বর্তমান ঠিকানা')),
                ('is_permanent_same_as_current', models.BooleanField(default=False, verbose_name='স্থায়ী ঠিকানা একই?')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='স্থায়ী ঠিকানা')),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='পিতার নাম')),
                ('fathers_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='পিতার মোবাইল')),
                ('fathers_nid', models.CharField(blank=True, max_length=20, null=True, verbose_name='পিতার এনআইডি')),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='মাতার নাম')),
                ('mothers_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='মাতার মোবাইল')),
                ('mothers_nid', models.CharField(blank=True, max_length=20, null=True, verbose_name='মাতার এনআইডি')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'পুরুষ'), ('Female', 'নারী'), ('Other', 'অন্যান্য')], default='Male', max_length=10, null=True, verbose_name='লিঙ্গ')),
                ('married', models.CharField(blank=True, choices=[('Yes', 'হ্যাঁ'), ('No', 'না')], default='No', max_length=5, null=True, verbose_name='বৈবাহিক অবস্থা')),
                ('last_education', models.CharField(blank=True, choices=[('SSC', 'এসএসসি'), ('HSC', 'এইচএসসি'), ('HONOURS', 'স্নাতক'), ('Others', 'অন্যান্য')], default='SSC', max_length=20, null=True, verbose_name='সর্বশেষ শিক্ষাগত যোগ্যতা')),
                ('last_education_other', models.CharField(blank=True, help_text='অন্যান্য হলে লিখুন', max_length=100, null=True, verbose_name='অন্যান্য শিক্ষাগত যোগ্যতা')),
                ('last_education_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='ফলাফল')),
                ('last_education_passing_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='পাসের বছর')),
                ('current_job_status', models.CharField(blank=True, choices=[('Unemployed', 'বেকার'), ('Employed', 'চাকরিজীবী'), ('Student', 'ছাত্র/ছাত্রী'), ('Business', 'ব্যবসা'), ('Others', 'অন্যান্য')], default='Unemployed', max_length=20, null=True, verbose_name='বর্তমান পেশার অবস্থা')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির তারিখ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেটের তারিখ')),
            ],
        ),
    ]
