# Generated by Django 5.2.1 on 2025-06-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentinfo_image'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcvagent',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_cvs_by_agent', to='accounts.agentinfo'),
        ),
    ]
