# Generated by Django 5.2.1 on 2025-07-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_customersupportreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupport',
            name='admin_unread',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customersupport',
            name='user_unread',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customersupportreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support/support_attachments/'),
        ),
    ]
