# Generated by Django 5.2.1 on 2025-06-17 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(help_text='Phone number must start with 0 and be exactly 11 digits.', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' and be exactly 11 digits long.", regex='^0\\d{10}$')])),
                ('purpose', models.CharField(choices=[('general', 'General Inquiry'), ('booking', 'Booking Request'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
