# Generated by Django 5.2.1 on 2025-06-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(choices=[('general', 'সাধারণ প্রশ্ন'), ('booking', 'বুকিং'), ('feedback', 'মতামত'), ('other', 'অন্যান্য ')], default='general', max_length=255),
        ),
    ]
