# Generated by Django 5.2.1 on 2025-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_contact_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(blank=True, choices=[('general', 'সাধারণ প্রশ্ন'), ('booking', 'বুকিং'), ('feedback', 'মতামত'), ('other', 'অন্যান্য ')], default='general', max_length=255, null=True),
        ),
    ]
