# Generated by Django 5.2.1 on 2025-06-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_contact_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(blank=True, choices=[('study_visa', 'স্টাডি ভিসা'), ('work_visa', 'ওয়ার্ক পারমিট ভিসা'), ('tourist_visa', 'ট্যুরিস্ট ভিসা'), ('agent_interest', 'এজেন্ট হতে আগ্রহী'), ('general', 'সাধারণ প্রশ্ন'), ('other', 'অন্যান্য ')], default='general', max_length=255, null=True),
        ),
    ]
