# Generated by Django 5.2.1 on 2025-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_contact_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Travel Core', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/', verbose_name='site_logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site_settings/logo_fav/', verbose_name='site_fav')),
                ('phone', models.CharField(blank=True, max_length=18, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=18, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('footer', models.CharField(blank=True, max_length=255)),
                ('footer_description', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('x', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
