# Generated by Django 5.2.1 on 2025-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_1', models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='স্লাইড ১ ইমেজ')),
                ('carousel_1_heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ১ শিরোনাম')),
                ('carousel_1_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ১ বিবরণ')),
                ('carousel_1_button_link', models.URLField(blank=True, null=True, verbose_name='স্লাইড ১ লিংক')),
                ('carousel_2', models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='স্লাইড ২ ইমেজ')),
                ('carousel_2_heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ২ শিরোনাম')),
                ('carousel_2_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ২ বিবরণ')),
                ('carousel_2_button_link', models.URLField(blank=True, null=True, verbose_name='স্লাইড ২ লিংক')),
                ('carousel_3', models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='স্লাইড ৩ ইমেজ')),
                ('carousel_3_heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ৩ শিরোনাম')),
                ('carousel_3_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='স্লাইড ৩ বিবরণ')),
                ('carousel_3_button_link', models.URLField(blank=True, null=True, verbose_name='স্লাইড ৩ লিংক')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
