# Generated by Django 5.2.1 on 2025-07-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
