# Generated by Django 5.2.1 on 2025-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trending',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
