# Generated by Django 5.2.1 on 2025-07-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0010_sitesettings_service_sitesettings_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
