# Generated by Django 5.2.1 on 2025-07-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_trending_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
