# Generated by Django 5.2.1 on 2025-07-12 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0013_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('address', models.TextField(verbose_name='ঠিকানা')),
                ('mobile_number', models.CharField(help_text='মোবাইল নম্বর অবশ্যই ০ দিয়ে শুরু হতে হবে এবং ১১ ডিজিটের হতে হবে।', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' and be exactly 11 digits long.", regex='^0\\d{10}$')], verbose_name='মোবাইল নম্বর')),
                ('appointment_date', models.DateField(verbose_name='অ্যাপয়েন্টমেন্টের তারিখ')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('confirmed', 'নিশ্চিত'), ('completed', 'সম্পন্ন'), ('cancelled', 'বাতিল')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
