# Generated by Django 5.2.1 on 2025-07-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0014_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_settings/chose/')),
                ('des1', models.TextField(blank=True, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='site_settings/chose/')),
                ('des2', models.TextField(blank=True, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='site_settings/chose/')),
                ('des3', models.TextField(blank=True, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='site_settings/chose/')),
                ('des4', models.TextField(blank=True, null=True)),
                ('img4', models.ImageField(blank=True, null=True, upload_to='site_settings/chose/')),
            ],
        ),
    ]
