# Generated by Django 5.2.1 on 2025-07-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0015_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
