# Generated by Django 5.2.1 on 2025-07-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0016_choose_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='site_settings/cv/')),
                ('title1', models.CharField(blank=True, max_length=250, null=True)),
                ('des1', models.TextField(blank=True, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='site_settings/cv/')),
                ('title2', models.CharField(blank=True, max_length=250, null=True)),
                ('des2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
