# Generated by Django 5.2.1 on 2025-07-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0017_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title_d',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
