# Generated by Django 5.2.1 on 2025-07-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0018_cv_title_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('des1', models.TextField()),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('des2', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'পেন্ডিং'), ('confirmed', 'নিশ্চিত'), ('completed', 'সম্পন্ন'), ('cancelled', 'বাতিল')], default='pending', max_length=20, verbose_name='অবস্থা'),
        ),
    ]
