# Generated by Django 5.2.1 on 2025-07-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0019_appointmentnotice_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotice',
            name='des3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentnotice',
            name='title3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentnotice',
            name='des1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointmentnotice',
            name='des2',
            field=models.TextField(null=True),
        ),
    ]
