# Generated by Django 5.2.1 on 2025-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0020_appointmentnotice_des3_appointmentnotice_title3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
