# Generated by Django 5.2.1 on 2026-01-21 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0021_sitesettings_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.TextField(verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(verbose_name='Preferred Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(verbose_name='Purpose of Appointment / Details'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='mobile_number',
            field=models.CharField(help_text='Format: 01XXXXXXXXX (must be 11 digits starting with 0)', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' followed by 10 digits (total 11 digits).", regex='^0\\d{10}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Notes / Remarks'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Appointment Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(blank=True, choices=[('study_visa', 'Study visa'), ('work_visa', 'Work visa'), ('tourist_visa', 'Tourist visa'), ('agent_interest', 'Agent interest'), ('general', 'General Question'), ('other', 'Other ')], default='general', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_1',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='Slide 1 - Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_1_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Slide 1 - Button URL'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_1_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 1 - Main Heading'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_1_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 1 - Subtext / Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_2',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='Slide 2 - Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_2_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Slide 2 - Button URL'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_2_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 2 - Main Heading'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_2_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 2 - Subtext / Description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_3',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/sliders/', verbose_name='Slide 3 - Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_3_button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Slide 3 - Button URL'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_3_heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 3 - Main Heading'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='carousel_3_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slide 3 - Subtext / Description'),
        ),
    ]
